#!/usr/bin/env sh

# bar settings
yabai -m config status_bar off
# yabai -m config external_bar all:0:12
# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
#
# yabai -m config window_shadow off

yabai -m config window_border on
yabai -m config window_border_width 2
# yabai -m config active_window_border_topmost off
# yabai -m config active_window_border_color 0xfffabd2f # yellow
yabai -m config active_window_border_color 0xff83a598 # blue
# yabai -m config active_window_border_color 0xffd3869b # purple
yabai -m config normal_window_border_color 0xff665c54
# yabai -m config insert_window_border_color 0xffd75f5f

# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 1.0

yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config window_topmost off

# general space settings
yabai -m config layout bsp
yabai -m config window_placement second_child
# yabai -m config top_padding $SPACEBAR_HEIGHT
# yabai -m config bottom_padding 10
# yabai -m config left_padding 10
# yabai -m config right_padding 10
# yabai -m config window_gap 10

# Float Windows
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Zscaler" manage=off

echo "yabai configuration loaded.."
