# https://clang.llvm.org/extra/clang-tidy/#id2
# https://clang.llvm.org/extra/clang-tidy/checks/list.html
Diagnostics:
    ClangTidy:
        Add:
            - cppcoreguidelines-*
            - performance-*
            - concurrency-*
            - performance-*
            - portability-*
            - readability-*
            - bugprone-*
            - modernize-*
            - google-*
            - boost-*
            - llvm-*
CompileFlags: # Tweak the parse settings
    Add: [-xc++, -Wall] # treat all files as C++, enable more warnings
