# https://clang.llvm.org/extra/clang-tidy/#id2
# https://clang.llvm.org/extra/clang-tidy/checks/list.html
Diagnostics:
    ClangTidy:
        Add:
            - cppcoreguidelines-*
            - performance-*
            - concurrency-*
            - performance-*
            - portability-*
            - readability-*
            - bugprone-*
            - modernize-*
            - google-*
            - boost-*
            - llvm-*
        Remove:
            # Annoying to suggest it everywhere
            - modernize-use-trailing-return-type
CompileFlags: # Tweak the parse settings
    Add: [
            # treat all files as C++
            -xc++,
            # use C++20
            -std=c++20,
            -Wall,
            -Wextra,
            -Wpedantic,
            -Weverything,
            # disable warnings about compatibility with C++98
            -Wno-c++98-compat,
            # circumvent this SDL2 bug on Ubuntu: 
            # https://bugs.launchpad.net/ubuntu/+source/libsdl2-ttf/+bug/1872023
            -I/usr/include/SDL2,
        ]
