require("config.settings")
require("config.keymaps")
require("config.colorscheme")
require("config.lsp")
require("config.completion")
require("config.treesitter")
require("config.telescope")
require("config.terminal")
require("config.git")
require("config.status_line")

require("colorizer").setup()
