-- require("config.evil_lualine")
require("config.indent")
require("config.lualine")
require("config.colorscheme")
require("config.completion")
require("config.treesitter")
require("config.telescope")
require("config.git")
require("config.terminal")
require("config.debugger")
require("config.whichkey")
require("config.dashboard")
require("config.tree")
